"""Demo script: generate the classic ASPECT convection-box cookbook via the middleware.

This script demonstrates the intended workflow for LLMs: instead of writing the
.prm file directly, the LLM supplies a structured answer dictionary, and the
middleware assembles the final .prm file with correct syntax.
"""

from pathlib import Path

from aspect_prm_builder import assembler, engine, schema, validator


def main():
    # 1. The LLM answers a set of concrete, schema-driven questions.
    answers = engine.build_from_answers(
        {
            "Dimension": 2,
            "Use years instead of seconds": False,
            "End time": 0.5,
            "Output directory": "output-convection-box",
            "Nonlinear solver scheme": "single Advection, single Stokes",
            "Pressure normalization": "surface",
            "Surface pressure": 0,
            "Geometry model.Model name": "box",
            "Geometry model.Box.X extent": 1,
            "Geometry model.Box.Y extent": 1,
            "Initial temperature model.Model name": "function",
            "Initial temperature model.Function.Variable names": "x,z",
            "Initial temperature model.Function.Function constants": "p=0.01, L=1, pi=3.1415926536, k=1",
            "Initial temperature model.Function.Function expression": "(1.0-z) - p*cos(k*pi*x/L)*sin(pi*z)",
            "Boundary temperature model.Fixed temperature boundary indicators": ["bottom", "top"],
            "Boundary temperature model.List of model names": ["box"],
            "Boundary temperature model.Box.Bottom temperature": 1,
            "Boundary temperature model.Box.Left temperature": 0,
            "Boundary temperature model.Box.Right temperature": 0,
            "Boundary temperature model.Box.Top temperature": 0,
            "Boundary velocity model.Tangential velocity boundary indicators": ["left", "right", "bottom", "top"],
            "Gravity model.Model name": "vertical",
            "Gravity model.Vertical.Magnitude": 1e4,
            "Material model.Model name": "simple",
            "Material model.Simple model.Reference density": 1,
            "Material model.Simple model.Reference specific heat": 1,
            "Material model.Simple model.Reference temperature": 0,
            "Material model.Simple model.Thermal conductivity": 1,
            "Material model.Simple model.Thermal expansion coefficient": 1,
            "Material model.Simple model.Viscosity": 1,
            "Formulation.Formulation": "Boussinesq approximation",
            "Mesh refinement.Initial global refinement": 4,
            "Mesh refinement.Initial adaptive refinement": 0,
            "Mesh refinement.Time steps between mesh refinement": 0,
            "Postprocess.List of postprocessors": [
                "velocity statistics",
                "temperature statistics",
                "heat flux statistics",
                "visualization",
            ],
            "Postprocess.Visualization.Time between graphical output": 0.01,
            "Solver parameters.Temperature solver tolerance": 1e-10,
        }
    )

    # 2. Validate the answers.
    errors = validator.validate_answers(answers, schema.build_schema())
    if errors:
        print("Validation errors:")
        for path, msg in errors:
            print(f"  {path}: {msg}")
        return 1

    # 3. Assemble the .prm file.
    header = (
        "A description of convection in a 2d box. Generated by the ASPECT "
        ".prm middleware from a structured answer dictionary."
    )
    prm_text = assembler.assemble_prm(answers, schema.build_schema(), header=header)

    output_dir = Path(__file__).parent / "generated_examples"
    output_dir.mkdir(exist_ok=True)
    output_path = output_dir / "convection_box_demo.prm"
    output_path.write_text(prm_text, encoding="utf-8")

    print(f"Generated: {output_path}")
    print("\n--- .prm file ---")
    print(prm_text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
