"""Example: how an LLM should interact with the middleware.

This script demonstrates the *intended* workflow for an LLM backend. Instead of
generating raw .prm text, the LLM produces a structured answer dictionary. The
middleware then validates, assembles, and serializes the final parameter file.

The example below rebuilds the van Keken et al. smooth benchmark from the
cookbooks.
"""

from pathlib import Path

from aspect_prm_builder import assembler, engine, schema, validator


def main():
    # These answers are exactly the kind of concrete, schema-driven values an LLM
    # should emit. No knowledge of ASPECT indentation or ``set`` syntax is needed.
    llm_answers = {
        "Dimension": 2,
        "Start time": 0,
        "End time": 2000,
        "Use years instead of seconds": False,
        "CFL number": 1.0,
        "Output directory": "output-van-keken-smooth",
        "Pressure normalization": "no",
        "Geometry model.Model name": "box",
        "Geometry model.Box.X extent": 0.9142,
        "Geometry model.Box.Y extent": 1.0,
        "Boundary velocity model.Tangential velocity boundary indicators": ["left", "right"],
        "Boundary velocity model.Zero velocity boundary indicators": ["bottom", "top"],
        "Material model.Model name": "simple",
        "Material model.Simple model.Reference density": 1010,
        "Material model.Simple model.Viscosity": 1e2,
        "Material model.Simple model.Thermal expansion coefficient": 0,
        "Material model.Simple model.Density differential for compositional field 1": -10,
        "Gravity model.Model name": "vertical",
        "Gravity model.Vertical.Magnitude": 10,
        "Initial temperature model.Model name": "function",
        "Initial temperature model.Function.Function expression": "0",
        "Compositional fields.Number of fields": 1,
        "Initial composition model.Model name": "function",
        "Initial composition model.Function.Variable names": "x,z",
        "Initial composition model.Function.Function constants": "pi=3.1415926",
        "Initial composition model.Function.Function expression": "0.5*(1+tanh((0.2+0.02*cos(pi*x/0.9142)-z)/0.02))",
        "Mesh refinement.Initial adaptive refinement": 0,
        "Mesh refinement.Strategy": ["composition"],
        "Mesh refinement.Initial global refinement": 7,
        "Mesh refinement.Time steps between mesh refinement": 0,
        "Mesh refinement.Coarsening fraction": 0.05,
        "Mesh refinement.Refinement fraction": 0.3,
        "Postprocess.List of postprocessors": [
            "visualization",
            "velocity statistics",
            "composition statistics",
        ],
        "Postprocess.Visualization.Output format": "vtu",
        "Postprocess.Visualization.Time between graphical output": 100,
    }

    answers = engine.build_from_answers(llm_answers)
    errors = validator.validate_answers(answers, schema.build_schema())
    if errors:
        print("Validation errors:")
        for path, msg in errors:
            print(f"  {path}: {msg}")
        return 1

    header = (
        "A description of the van Keken et al. benchmark using smooth initial "
        "conditions. Generated by the ASPECT .prm middleware from a structured "
        "answer dictionary."
    )
    prm_text = assembler.assemble_prm(answers, schema.build_schema(), header=header)

    output_dir = Path(__file__).parent / "generated_examples"
    output_dir.mkdir(exist_ok=True)
    output_path = output_dir / "van_keken_smooth_demo.prm"
    output_path.write_text(prm_text, encoding="utf-8")

    print(f"Generated: {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
